# Generated by Django 4.2.9 on 2024-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
